config/routes.rb
Avalon::Application.routes.draw do
  Blacklight.add_routes(self, except: [:bookmarks, :feedback, :catalog])

  match "catalog/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  match "catalog", :to => 'catalog#index', :as => 'catalog_index'

  root :to => "catalog#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, format: false
  devise_scope :user do 
    match '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session
    match '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session
  end
  match "/authorize", to: 'derivatives#authorize'
  match "/autocomplete", to: 'object#autocomplete'

  match "object/:id", to: 'object#show'
  resources :media_objects, except: [:create] do
    member do
      put :update_status
      get :remove
      get :progress, :action => :show_progress
      get 'content/:datastream', :action => :deliver_content, :as => :inspect
      get 'track/:part', :action => :show, :as => :indexed_section
      get 'section/:content', :action => :show, :as => :pid_section
      get 'tree', :action => :tree, :as => :tree
    end
  end
  resources :master_files, except: [:new, :index] do
    member do
      get  'thumbnail', :to => 'master_files#get_frame', :defaults => { :type => 'thumbnail' }
      get  'poster',    :to => 'master_files#get_frame', :defaults => { :type => 'poster' }

      post 'thumbnail', :to => 'master_files#set_frame', :defaults => { :type => 'thumbnail', :format => 'html' }
      post 'poster',    :to => 'master_files#set_frame', :defaults => { :type => 'poster', :format => 'html' }
      post 'still',     :to => 'master_files#set_frame', :defaults => { :format => 'html' }
      get :embed
    end
  end

  match '/media_objects/:media_object_id/section/:id/embed' => 'master_files#embed'

  resources :derivatives, only: [:create]
  
  resources :comments, only: [:index, :create]

  namespace :admin do
    resources :groups, except: [:show] do 
      collection do 
        put 'update_multiple'
      end
      member do
        put 'update_users'
      end
    end
    resources :collections do
      member do
        get 'edit'
        get 'remove'
      end
    end
  end

  resources :dropbox, :only => [] do
    collection do
      delete :bulk_delete
    end
  end

  mount AboutPage::Engine => '/about(.:format)'
  

end

app/controllers/media_objects_controller.rb
# Copyright 2011-2014, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

require 'avalon/controller/controller_behavior'

class MediaObjectsController < ApplicationController 
  include Avalon::Workflow::WorkflowControllerBehavior
  include Avalon::Controller::ControllerBehavior
  include Hydra::AccessControlsEnforcement

#  before_filter :enforce_access_controls
  before_filter :inject_workflow_steps, only: [:edit, :update]
  before_filter :load_player_context, only: [:show, :show_progress, :remove]

  # Catch exceptions when you try to reference an object that doesn't exist.
  # Attempt to resolve it to a close match if one exists and offer a link to
  # the show page for that item. Otherwise ... nothing!
  rescue_from ActiveFedora::ObjectNotFoundError do |exception|
    render '/errors/unknown_pid', status: 404
  end
 
  def new
    collection = Admin::Collection.find(params[:collection_id])
    authorize! :read, collection

    @mediaobject = MediaObjectsController.initialize_media_object(user_key)
    @mediaobject.workflow.origin = 'web'
    @mediaobject.collection = collection
    @mediaobject.save(:validate => false)

    redirect_to edit_media_object_path(@mediaobject)
  end

  def custom_edit
    authorize! :update, @mediaobject
    if ['preview', 'structure', 'file-upload'].include? @active_step
      @masterFiles = load_master_files
    end

    if 'preview' == @active_step 
      @currentStream = params[:content] ? set_active_file(params[:content]) : @masterFiles.first
      @token = @currentStream.nil? ? "" : StreamToken.find_or_create_session_token(session, @currentStream.mediapackage_id)
      @currentStreamInfo = @currentStream.nil? ? {} : @currentStream.stream_details(@token, default_url_options[:host])

      if (not @masterFiles.empty? and @currentStream.blank?)
        @currentStream = @masterFiles.first
        flash[:notice] = "That stream was not recognized. Defaulting to the first available stream for the resource"
      end
    end

    if 'access-control' == @active_step 
      @groups = @mediaobject.local_read_groups
      @users = @mediaobject.read_users
      @virtual_groups = @mediaobject.virtual_read_groups
      @visibility = @mediaobject.visibility

      @addable_groups = Admin::Group.non_system_groups.reject { |g| @groups.include? g.name }
      @addable_courses = Course.all.reject { |c| @virtual_groups.include? c.context_id }
    end
  end

  def custom_update
    authorize! :update, @mediaobject
    flash[:notice] = @notice
  end

  def show
    authorize! :read, @mediaobject
    respond_to do |format|
      format.html do
	if (not @masterFiles.empty? and @currentStream.blank?) then
          redirect_to media_object_path(@mediaobject.pid), flash: { notice: 'That stream was not recognized. Defaulting to the first available stream for the resource' }
        else 
          render
        end
      end
      format.json do
        render :json => @currentStreamInfo 
      end
    end
  end

  def show_progress
    authorize! :read, @mediaobject
    overall = { :success => 0, :error => 0 }

    result = Hash[
      @masterFiles.collect { |mf| 
        mf_status = {
          :status => mf.status_code,
          :complete => mf.percent_complete.to_i,
          :success => mf.percent_succeeded.to_i,
          :error => mf.percent_failed.to_i,
          :operation => mf.operation,
          :message => mf.error.try(:sub,/^.+:/,'')
        }
        if mf.status_code == 'FAILED'
          mf_status[:error] = 100-mf_status[:success]
          overall[:error] += 100
        else
          overall[:success] += mf_status[:complete]
        end
        [mf.pid, mf_status]
      }
    ]
    overall.each { |k,v| overall[k] = [0,[100,v.to_f/@masterFiles.length.to_f].min].max.round }

    if overall[:success]+overall[:error] > 100
      overall[:error] = 100-overall[:success]
    end

    result['overall'] = overall
    respond_to do |format|
      format.any(:xml, :json) { render request.format.to_sym => result }
    end
  end

  # This sets up the delete view which is an item preview with the ability
  # to take the item out of the system for good (by POSTing to the destroy
  # action)
  def remove 
    #@previous_view = media_object_path(@mediaobject)
  end

  def destroy
    media_object = MediaObject.find(params[:id])
    authorize! :destroy, media_object
    message = "#{media_object.title} (#{params[:id]}) has been successfuly deleted"

    # attempt to stop the matterhorn processing job
    media_object.parts.each(&:destroy)
    media_object.parts.clear
    
    media_object.destroy
    
    redirect_to root_path, flash: { notice: message }
  end

  # Sets the published status for the object. If no argument is given then
  # it will just toggle the state.
  def update_status
    media_object = MediaObject.find(params[:id])
    authorize! :update, media_object
    
    case params[:status]
      when 'publish'
        media_object.publish!(user_key)
      when 'unpublish'
        media_object.publish!(nil) if can?(:unpublish, media_object)   
    end

    # additional save to set permalink
    media_object.save( validate: false )
    
    redirect_to :back
  end

  # Sets the published status for the object. If no argument is given then
  # it will just toggle the state.
  def tree
    @mediaobject = MediaObject.find(params[:id])
    authorize! :inspect, @mediaobject

    respond_to do |format|
      format.html { 
        render 'tree', :layout => !request.xhr?
      }
      format.json { 
        result = { @mediaobject.pid => {} }
        @mediaobject.parts_with_order.each do |mf|
          result[@mediaobject.pid][mf.pid] = mf.derivatives.collect(&:pid)
        end
        render :json => result 
      }
    end
  end

  def self.initialize_media_object( user_key )
    mediaobject = MediaObject.new( avalon_uploader: user_key )

    mediaobject
  end

  def build_context
    params.merge!({mediaobject: model_object, user: user_key, ability: current_ability})
  end

  protected

  def load_master_files
    @mediaobject.parts_with_order
  end

  def load_player_context
    @mediaobject = MediaObject.find(params[:id])

    if params[:part]
      index = params[:part].to_i-1
      if index < 0 or index > @mediaobject.section_pid.length
        raise ActiveFedora::ObjectNotFoundError
      end
      params[:content] = @mediaobject.section_pid[index]
    end
    @masterFiles = load_master_files
    @currentStream = params[:content] ? set_active_file(params[:content]) : @masterFiles.first
    @token = @currentStream.nil? ? "" : StreamToken.find_or_create_session_token(session, @currentStream.mediapackage_id)
    # This rescue statement seems a bit dodgy because it catches *all*
    # exceptions. It might be worth refactoring when there are some extra
    # cycles available.
    @currentStreamInfo = @currentStream.nil? ? {} : @currentStream.stream_details(@token, default_url_options[:host])
 end

  # The goal of this method is to determine which stream to provide to the interface
  #
  # for immediate playback. Eventually this might be replaced by an AJAX call but for
  # now to update the stream you must do a full page refresh.
  # 
  # If the stream is not a member of that media object or does not exist at all then
  # return a nil value that needs to be handled appropriately by the calling code
  # block
  def set_active_file(file_pid = nil)
    unless (@mediaobject.parts.blank? or file_pid.blank?)
      @mediaobject.parts.each do |part|
        return part if part.pid == file_pid
      end
    end

    # If you haven't dropped out by this point return an empty item
    nil
  end 
end

app/helpers/media_objects_helper.rb
# Copyright 2011-2014, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

module MediaObjectsHelper
      # Quick and dirty solution to the problem of displaying the right template.
      # Quick and dirty also gets it done faster.
      def current_step_for(status=nil)
        if status.nil?
          status = HYDRANT_STEPS.first
        end
        
        HYDRANT_STEPS.template(status)
      end
     
      # Based on the current context it will choose which class should be
      # applied to the display. If you are not using Twitter Bootstrap or
      # want different defaults then change them here.
      #
      # The context here is the media_object you are working with.
      def class_for_step(context, step)  
        css_class = case 
          # when context.workflow.current?(step)
          #   'nav-info'
          when context.workflow.completed?(step)
            'nav-success'
          else 'nav-disabled' 
          end

        css_class
     end

     def dropbox_url collection
        ic = Iconv.new('UTF-8//IGNORE', 'UTF-8')
        path = URI::Parser.new.escape(collection.dropbox_directory_name, %r{[/\\%& #]})
        url = File.join(Avalon::Configuration.lookup('dropbox.upload_uri'), path)
        ic.iconv(url)
     end
end

app/views/media_objects/_access_control.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<%= twitter_bootstrap_form_for @mediaobject, html: { class: "form-horizontal", id: 'access_control_form'}  do |vid| %>
  <%= hidden_field_tag :step, @active_step %>

  <%= render "modules/access_control", {form: vid, object: @mediaobject, visibility: @mediaobject.visibility, hidden: @mediaobject.hidden?} %>	

  <%= render "workflow_buttons", form: vid %>	
<% end #form_for %>		

app/views/media_objects/_administrative_links.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% if can? :update, @mediaobject %>
  <div class="row-fluid">
      <p>
        <ul class="unstyled hidden">
          <li>
            <% if @mediaobject.published? %>
              <span class="label label-success">Published</span> Authorized users can view the item</li>
            <% else %>
              <span class="label label-important">Unpublished</span> Users cannot view the item</li>
            <% end %>
          <li>
            <% unless @mediaobject.discover_groups.include? "nobody" %>
              <span class="label label-success">Visible</span> Users can search for the item</li>
            <% else %>
              <span class="label label-important">Hidden</span> Users cannot search for the item</li>
            <% end %>
        </ul>
      </p>

      <div id="administrative_options" style="margin-bottom:1em;">

      <% if @mediaobject.published? %>
        <% if can?(:unpublish, @mediaobject) %>
          <%= link_to 'Unpublish', update_status_media_object_path(@mediaobject, :status => 'unpublish'), method: :put, class: 'btn' %>
        <% end %>
      <% else %>
        <%= link_to 'Publish', update_status_media_object_path(@mediaobject, :status => 'publish'), method: :put, class: 'btn' %>
      <% end %>


        <%= link_to 'Edit', edit_media_object_path(@mediaobject), class: 'btn' %>
        <%# This might not be the best approach because it makes accidental 
            deletion possible just by following a link. Need to revisit when
            extra cycles are available %>

        <% if can? :destroy, @mediaobject %>
          <%= link_to 'Delete', remove_media_object_path(@mediaobject), class: 'btn btn-danger' %>
        <% end %>
      </div>
  </div>
<% end %>

app/views/media_objects/_basic_metadata.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% if flash[:error].present? %>
  <div class='alert alert-error' style='display: inline-table;'><%= flash[:error] %></div>
<% end %>

<p>Fields followed by an asterisk (*) are required.</p>
<%= form_for @mediaobject, html: { class: 'form-vertical', id: 'basic_metadata_form' } do |media| %>
  <%= hidden_field_tag :step, @active_step %>
  
  <%# This is not very DRY for a first pass but that can come once it shows some promise %>
  <%= render partial: 'text_field', 
             locals: {media: media, field: :title, 
                      options: {required: true, tooltip: true}} %>

  <%# This clearly needs to be refactored once it works right and there is 
      proper test coverage %>
  <%= render partial: 'text_fields',
             locals: {media: media, field: :creator,
                      count: [3, @mediaobject.creator.length].max,
                      text_label: 'Main contributor(s)', 
                      options: {required: true, tooltip: true, dynamic: true}} %>
                    
  <%= render partial: 'text_field', 
             locals: {media: media, field: :date_issued,
                      text_label: 'Publication date',
                      options: {tooltip: true, required: true}} %>

  <%= render partial: 'text_field', 
             locals: {media: media, field: :date_created,
                      text_label: 'Creation date',
                      options: {tooltip: true}} %>

  <%= render partial: 'text_area', 
             locals: {media: media, field: :abstract,
                      text_label: 'Summary',
                      options: {tooltip: true}} %>

  <%= render partial: 'text_fields',
             locals: {media: media, field: :contributor,
                      count: [3, @mediaobject.contributor.length].max,
                      text_label: 'Contributor(s)', 
                      options: {tooltip: true, dynamic: true}} %>

  <%= render partial: 'text_fields',
             locals: {media: media, field: :publisher,
                      count: [3, @mediaobject.publisher.length].max,
                      text_label: 'Publisher(s)', 
                      options: {tooltip: true, dynamic: true}} %>

  <%= render partial: 'text_fields',
             locals: {media: media, field: :genre,
                      count: [3, @mediaobject.genre.length].max,
                      text_label: 'Genre(s)', 
                      options: {tooltip: true, dynamic: true}} %>
  <%= render partial: 'text_fields',
             locals: {media: media, field: :topical_subject,
                      count: [3, @mediaobject.topical_subject.length].max,
                      text_label: 'Subject(s)', 
                      options: {tooltip: true, dynamic: true}} %>
  <%= render partial: 'text_fields',
             locals: {media: media, field: :temporal_subject,
                      count: [3, @mediaobject.temporal_subject.length].max,
                      text_label: 'Time period(s)', 
                      options: {tooltip: true, dynamic: true}} %>
  <%= render partial: 'text_fields',
             locals: {media: media, field: :geographic_subject,
                      count: [3, @mediaobject.geographic_subject.length].max,
                      text_label: 'Location(s)', 
                      options: {tooltip: true, dynamic: true}} %>
  <%= render partial: 'text_field',
             locals: {media: media, field: :permalink,
                      text_label: 'Permalink', 
                      options: {tooltip: true}} %>

  <%= render 'workflow_buttons', form: media %>
<% end %>

<% content_for :page_scripts do %>
  <%= javascript_include_tag 'dynamic_fields' %>
<script>
  $().ready(function() {
    DynamicFields.initialize();
  });
</script>
<% end %>

app/views/media_objects/_dropbox.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<div id="dropbox_modal" class="modal hide fade big-modal" tabindex="-1" role="dialog" aria-labelledby="dropbox_modal_label">
  <%= form_tag(master_files_path) do -%>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
      <%= render partial: "dropbox_file_navigator", locals: {file_set: @dropbox_files} %>
    </div>
    <div class="modal-footer">
      <p style="clear:both">
        <% if can? :destroy, @mediaobject.collection %>
          <%= hidden_field_tag 'collection_id', @mediaobject.collection.id %>
          <%= link_to 'Remove Selected Files', bulk_delete_dropbox_index_path, class: 'btn btn-danger pull-left remove-selected-files' %>
        <% end %>
        <%= button_tag "Close", type: "button", class: "btn", 'data-dismiss'=>'modal' %>
        <%= button_tag "Attach Selected Files", class: "btn", donot_advance: true %>
      </p>
      <span class="checkbox inline fileupload-exists">
        <%= check_box_tag(:workflow, 'skip_transcoding', false ) %>
        <%= label_tag(:skip_transcoding) do %>
          <div style="font-size: inherit;" class="tooltip-help" 
            data-title="<%= "something" %>" data-tooltip="#skip-transcoding-dropbox-tooltip">
            Skip transcoding                    
          </div>
        <% end %>
      </span>

      <div class="collapse form-tooltip equal-height" id="skip-transcoding-dropbox-tooltip">
        <button class="close">&times;</button>
         <p><%= t("file_upload_tip.skip_transcoding").html_safe %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/media_objects/_dropbox_details.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<div class="well well-info muted">
  Dropbox location: <em><%= dropbox_url(@mediaobject.collection) %></em>
  <br/>
  Contact your system administrator for more information.
  <br/>
</div>

app/views/media_objects/_sections.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<%# Partial once the layout makes sense %>
      <% show_progress = sections.any? { |s| not s.succeeded? } %>
      <% unless (sections.blank? or sections.length == 1) and not show_progress %>
      <section class="whitespace" id="segments">
        <legend><i class="icon-list-alt"></i> Sections</legend>
          <ol id="section_links">
            <% sections.each_with_index do |section,i| %>
              <li class="<%= show_progress ? 'progress-indented' : ''%>">
                <%# If the label has not been set use the file name as a default %>
                <% if show_progress %>
                  <span class="progress progress-inline">
                    <div class='bar bar-success' style='width:0%'></div>
                    <div class='bar bar-danger' style='width:0%'></div>
                    <div class='bar bar-warning' style='width:0%'></div>
                  </span>
                <% end %>
                <%=
                  link_to stream_label_for(section),
                    pid_section_media_object_path(mediaobject, section.pid),
                    data: {segment: section.pid, is_video: section.is_video?, share_link: share_link_for(section)},
                    class: (section.pid == activeStream.pid ? 'current-stream' : nil)
                %>
                <% unless section.duration.blank? %>
                  (<%= milliseconds_to_formatted_time(section.duration.to_i) %>)
                <% end %>
                <% if show_progress %>
                  <div class="status-detail alert" style="display: none"></div>
                <% end %>
              </li>
              <% end %>
          </ol>
       </section>
       <% end %>

app/views/media_objects/_share.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>

<ul class="nav nav-tabs share-tabs">
  <li class="active"><a href="#link-tab" data-toggle="tab">Share this resource</a></li>
  <li><a href="#embed-tab" data-toggle="tab">Embed</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="link-tab">
    <p class="muted">Copy the link below to share this resource</p>
    <form role="form">
      <div class="form-group">
        <label for="link-object">Item</label>
        <input type="text" class="span5 form-control" id="link-object" value="<%= share_link_for(@mediaobject) %>" onClick="this.select();">
      </div>
      <div class="form-group">
        <label for="link-section">Section</label>
        <% if @currentStream.present? %>
          <input type="text" class="span5 form-control" id="link-section" value="<%= share_link_for(@currentStream) %>" onClick="this.select();">
        <% else %>
          <p class="muted"> <%= I18n.t('media_object.empty_share_section_permalink_notice') %> </p>
        <% end %>
      </div>
    </form>
  </div>
  
  <div class="tab-pane" id="embed-tab">
    <% if @currentStream.present? %>
      <p class="muted">Copy the text below to embed this resource</p>
      <textarea class="span6" rows="3" id="embed-part" onClick="this.select();">
        <%= @currentStream.embed_code(MasterFile::EMBED_SIZE[:medium], { urlappend: '/embed' }) %>
      </textarea>
    <% else %>
      <p class="muted"> <%= I18n.t('media_object.empty_share_link_notice') %> </p>
    <% end %>
  </div>
</div>

<% content_for :page_scripts do %>

<script>
  $(document).ready(function() {
    $(document).on('streamswitch', function(e, stream_info){
      var shareLink = $('a.current-stream').data('share-link')
      $('#link-section').val(shareLink);
      if (stream_info != null) {
        $('#embed-part').text(stream_info.embed_code);
      }
    });
    $('.share-tabs a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
    });
  })
</script>

<% end %>

app/views/media_objects/_text_area.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% default_label = field.to_s %>
<% text_label ||= default_label.humanize %>
<% display_label = text_label || default_label.humanize %>
<% options ||= {} %>

<!-- <%= default_label.humanize %> field -->
  <div class="control-group">
    <%= render partial: "modules/tooltip", locals: { media: media, field: field, default_label: default_label, text_label: text_label, display_label: display_label, options: options } %>

    <div class="controls">
      <%= media.text_area field, rows: 10, class: 'span8' %>
    </div>
  </div>