config/routes.rb
Avalon::Application.routes.draw do
  Blacklight.add_routes(self, except: [:bookmarks, :feedback, :catalog])

  match "catalog/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  match "catalog", :to => 'catalog#index', :as => 'catalog_index'

  root :to => "catalog#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, format: false
  devise_scope :user do 
    match '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session
    match '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session
  end
  match "/authorize", to: 'derivatives#authorize'
  match "/autocomplete", to: 'object#autocomplete'

  match "object/:id", to: 'object#show'
  resources :media_objects, except: [:create] do
    member do
      put :update_status
      get :remove
      get :progress, :action => :show_progress
      get 'content/:datastream', :action => :deliver_content, :as => :inspect
      get 'track/:part', :action => :show, :as => :indexed_section
      get 'section/:content', :action => :show, :as => :pid_section
      get 'tree', :action => :tree, :as => :tree
    end
  end
  resources :master_files, except: [:new, :index] do
    member do
      get  'thumbnail', :to => 'master_files#get_frame', :defaults => { :type => 'thumbnail' }
      get  'poster',    :to => 'master_files#get_frame', :defaults => { :type => 'poster' }

      post 'thumbnail', :to => 'master_files#set_frame', :defaults => { :type => 'thumbnail', :format => 'html' }
      post 'poster',    :to => 'master_files#set_frame', :defaults => { :type => 'poster', :format => 'html' }
      post 'still',     :to => 'master_files#set_frame', :defaults => { :format => 'html' }
      get :embed
    end
  end

  match '/media_objects/:media_object_id/section/:id/embed' => 'master_files#embed'

  resources :derivatives, only: [:create]
  
  resources :comments, only: [:index, :create]

  namespace :admin do
    resources :groups, except: [:show] do 
      collection do 
        put 'update_multiple'
      end
      member do
        put 'update_users'
      end
    end
    resources :collections do
      member do
        get 'edit'
        get 'remove'
      end
    end
  end

  resources :dropbox, :only => [] do
    collection do
      delete :bulk_delete
    end
  end

  mount AboutPage::Engine => '/about(.:format)'
  

end

app/controllers/catalog_controller.rb
# Copyright 2011-2014, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController  
  include Blacklight::Catalog
  # Extend Blacklight::Catalog with Hydra behaviors (primarily editing).
  include Hydra::Controller::ControllerBehavior
  include Hydra::PolicyAwareAccessControlsEnforcement
  
	# This applies appropriate access controls to all solr queries
  self.solr_search_params_logic += [:add_access_controls_to_solr_params_if_not_admin]
  
  # This filters out objects that you want to exclude from search results, like FileAssets
  self.solr_search_params_logic += [:exclude_unwanted_models]
  self.solr_search_params_logic += [:only_wanted_models]
  self.solr_search_params_logic += [:only_published_items]
  self.solr_search_params_logic += [:limit_to_non_hidden_items]

  configure_blacklight do |config|
    config.http_method = :post
    config.default_solr_params = { 
      :qt => 'search',
      :rows => 10
    }

    # solr field configuration for search results/index views
    config.index.show_link = 'title_tesi'
    config.index.record_display_type = 'has_model_ssim'

    # solr field configuration for document/show views
    config.show.html_title = 'title_tesi'
    config.show.heading = 'title_tesi'
    config.show.display_type = 'has_model_ssim'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    config.add_facet_field 'format_sim', :label => 'Format', :limit => 5, :expanded => true
    # Eventually these need to be merged into a single facet
    config.add_facet_field 'creator_sim', :label => 'Main contributor', :limit => 5
    #TODO add "Date" facet that points to issue date in mediaobject
    config.add_facet_field 'date_sim', :label => 'Date', :limit => 5
    config.add_facet_field 'genre_sim', :label => 'Genres', :limit => 5
    config.add_facet_field 'collection_ssim', :label => 'Collection', :limit => 5
    config.add_facet_field 'unit_ssim', :label => 'Unit', :limit => 5


    # Hide these facets if not a Collection Manager
    config.add_facet_field 'workflow_published_sim', :label => 'Published', :limit => 5, :if_user_can => [:create, MediaObject], :group=>"workflow"
    config.add_facet_field 'created_by_sim', :label => 'Created by', :limit => 5, :if_user_can => [:create, MediaObject], :group=>"workflow"
    config.add_facet_field 'read_access_virtual_group_ssim', :label => 'External Group', :limit => 5, :if_user_can => [:create, MediaObject], :group=>"workflow", :helper_method => :vgroup_display

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys
    #use this instead if you don't want to query facets marked :show=>false
    #config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys    


    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field 'creator_ssim', :label => 'Main contributors:', :helper_method => :contributor_index_display 
    config.add_index_field 'date_ssi', :label => 'Date:' 
    config.add_index_field 'summary_ssi', label: 'Summary:', :helper_method => :description_index_display

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 
    config.add_show_field 'title_tesi', :label => 'Title' 
    config.add_show_field 'format_sim', :label => 'Format' 
    config.add_show_field 'creator_sim', :label => 'Creator' 
    config.add_show_field 'language_sim', :label => 'Language'
    config.add_show_field 'date_ssi', label: 'Date'
    config.add_show_field 'abstract_sim', label: 'Abstract'
    config.add_show_field 'location_sim', label: 'Locations'
    config.add_show_field 'time_period_sim', label: 'Time periods'
    config.add_show_field 'contributor_sim', label: 'Contributors'
    config.add_show_field 'publisher_sim', label: 'Publisher'
    config.add_show_field 'genre_sim', label: 'Genre'
    config.add_show_field 'publication_location_sim', label: 'Place of publication'
    config.add_show_field 'terms_sim', label: 'Terms'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    config.add_search_field 'all_fields', :label => 'All Fields'

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields. 
    config.add_search_field('title') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params. 
      field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      field.solr_local_parameters = { 
        :qf => '$title_qf',
        :pf => '$title_pf'
      }
    end
    
    config.add_search_field('creator') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'creator' }
      field.solr_local_parameters = { 
        :qf => '$creator_qf',
        :pf => '$creator_pf'
      }
    end
    
    # Specifying a :qt only to show it's possible, and so our internal automated
    # tests can test it. In this case it's the same as 
    # config[:default_solr_parameters][:qt], so isn't actually neccesary. 
    config.add_search_field('subject') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'subject' }
      field.qt = 'search'
      field.solr_local_parameters = { 
        :qf => '$subject_qf',
        :pf => '$subject_pf'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, title_tesi asc, date_ssi desc', :label => 'Relevance'
    config.add_sort_field 'date_ssi desc, title_tesi asc', :label => 'Year'
    config.add_sort_field 'creator_ssi asc, title_tesi asc', :label => 'Main contributor'
    config.add_sort_field 'title_tesi asc, date_ssi desc', :label => 'Title'

    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5
  end

  def only_wanted_models(solr_parameters, user_parameters)
    solr_parameters[:fq] ||= []
    solr_parameters[:fq] << 'has_model_ssim:"info:fedora/afmodel:MediaObject"'
  end

  def only_published_items(solr_parameters, user_parameters)
    if cannot? :create, MediaObject
      solr_parameters[:fq] ||= []
      solr_parameters[:fq] << 'workflow_published_sim:"Published"'
    end
  end

  def limit_to_non_hidden_items(solr_parameters, user_parameters)
    if cannot? :create, MediaObject
      solr_parameters[:fq] ||= []
      solr_parameters[:fq] << '!hidden_bsi:true'
    end
  end

app/views/catalog/_document_header.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% # header bar for doc items in index view -%>
<div class="documentHeader clearfix">
  <% # main title container for doc partial view -%>
    <h5 class="index_title"><%= t('blacklight.search.documents.counter', :counter => (document_counter + 1 + @response.params[:start].to_i)) %>
      <%= link_to_document document, :label => search_result_label(document), :counter => (document_counter + 1 + @response.params[:start].to_i) %>
    </h5>
  
  <% # bookmark functions for items/docs -%>
  <%= render_index_doc_actions document, :wrapping_class => "documentFunctions span2" %>
</div>

app/views/catalog/_facet_group.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% # container for a facet/limit group %>
<% if has_facet_values? facet_field_names(groupname) %>
<div id="facets<%= "-#{groupname}" unless groupname.nil?%>" class="facets sidenav">
 
  <h4 data-toggle="collapse" data-target="#facets<%= "-#{groupname}" unless groupname.nil?%>-collapse">

      <a class="btn btn-navbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </a>
  	<%= groupname.blank? ? t('blacklight.search.facets.title') : t("blacklight.search.facets-#{groupname}.title") %>

  </h4>
  <div id="facets<%= "-#{groupname}" unless groupname.nil?%>-collapse" class="facets-collapse">
    <%= render_facet_partials facet_field_names(groupname)%>
  </div>
</div>
<% end %>

app/views/catalog/_facet_layout.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<div class="facet_limit blacklight-<%= facet_field.field.parameterize %>">
  <h5 data-toggle="collapse" data-target="ul#<%= solr_fname.parameterize %>"><%= facet_field.label -%> <i class="icon-chevron"></i></h5>
  <%= yield %>
</div>

app/views/catalog/_facet_limit.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<%# pulled in from blacklight to add autoexpand support %>
<ul id="<%= solr_fname.parameterize %>" class="collapse <% if expand_facet? facet_field %>in<% end %>">
 <% paginator =    
      Blacklight::Solr::FacetPaginator.new(display_facet.items,        
        :limit => facet_limit_for(solr_field))
  %>
  <% paginator.items.each do |item| -%>
    <li>
    <% if facet_in_params?( solr_field, item.value ) %>              
        <%= render_selected_facet_value(solr_field, item) %>              
      <% else %>              
        <%= render_facet_value(solr_field, item) %>              
    <% end -%>
    </li>
  <% end %>

  <% if(paginator.has_next?)  %>
    <li class="more_facets_link"><%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %></li>
  <% end %>

</ul>

app/views/catalog/_facets.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% # main container for facets/limits menu -%>
<% facet_group_names.each do |groupname| %>
  <%= render partial: "facet_group", locals: {groupname: groupname} %>
<% end %>

app/views/catalog/_home_text.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% if flash[:notice].present? %>
<div class="clearfix" id="alerts">
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>  
</div>
<% end %>

<h2>Sample Content</h2>

<ul class="thumbnails">
  <li class="span3"><h5>Featured Collection</h5><a href="#" class="thumbnail"><%= image_tag "Nutcracker-Ballet.png", alt: "Featured Collection" %></a></li>
  <li class="span3"><h5>Featured Video</h5><a href="#" class="thumbnail"><%= image_tag "Charlie-McCarthy.png", alt: "Featured Collection" %></a></li>
  <li class="span3"><h5>Featured Audio</h5><a href="#" class="thumbnail"><%= image_tag "Chucky-Lou.png", alt: "Featured Collection" %></a></li>
</ul>

<h4>Using the System</h4>

<p>Avalon houses audio and video collections. Use the search box, or browse using the terms on the left side to discover content. Some content is only available when you sign in.  Sign in with your ID and passphrase.</p>

app/views/catalog/_index_list_media_object.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<div class="result clearfix">
  <div class="span2">
    <% if image_url = image_for(document) %>
      <%= link_to(media_object_path(document[:id]), {class: 'result-thumbnail'}) do %>
        <%= image_tag( image_url ) %>
      <% end %>
    <% else %>
      <%= image_tag 'no_icon.png', class: 'result-thumbnail' %>
    <% end %>
  </div>

  <ul class="span6 result-list">
    <% index_fields.each do |solr_fname, field| -%>
      <% if should_render_index_field? document, field %>
              <li class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_label :field => solr_fname %>
                <span class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_value :document => document, :field => solr_fname %></span>
              </li>
      <% end -%>
    <% end -%>
  </ul>
</div>

app/views/catalog/_search_form.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
 <div class="span12">
  <%= form_tag catalog_index_path, :method => :get, :class => 'search-query-form form-search' do %>
    <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %> 

	<%= hidden_field_tag "search_field", "all_fields" %>
    <div>
      <%= text_field_tag :q, params[:q], class: "search_q q", 
        id: "appendedInputButtons" %>
      <button type="submit" class="btn btn-primary">
        <span class="submit-search-text">Search</span>
        <i class="icon-search icon-white"></i>
      </button>
    </div>
  <% end %>
</div>

app/views/catalog/index.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% content_for :title do %>
  <% if has_search_parameters? %>
    <% if params[:q].present? %><%= params[:q] %> - <% end %> Search Results
  <% end %>
<% end %>


<% content_for :additional_head_content do %>
  <link rel="alternate" type="application/xml" title="Solr" href="<%=build_solr_request_from_response%>">
<% end %>
<%# Index partial pulled in to declare this hidden div for more facet links since it was declared in blacklight's layout which we don't use %>
<div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>

<div class="row">
  <div id="sidebar" class="span3">
   <%= render :partial=>'facets' %>
  </div><!--/well -->

  <div id="content" class="span9">
    <% unless has_search_parameters? %>
	    <%# if there are no input/search related params, display the "home" partial -%>
	    <%= render 'home' %>
    <% else %>
      <h2 class="hide-text top-content-title"><%= t('blacklight.search.search_results_header') %></h2>
      <% @page_title = t('blacklight.search.title', :application_name => application_name) %>
      <% extra_head_content << render_opensearch_response_metadata.html_safe %>
	    <%= render :partial => 'did_you_mean' %>
      <%= render :partial => 'constraints' %>
	    <%= render 'sort_and_per_page' %>
      <h2 class="hide-text"><%= t('blacklight.search.search_results') %></h2>
	    <%= render_document_index %>
	    <%= render 'results_pagination' %>
    <% end %>
  </div>
</div>