config/routes.rb
Avalon::Application.routes.draw do
  Blacklight.add_routes(self, except: [:bookmarks, :feedback, :catalog])

  match "catalog/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  match "catalog", :to => 'catalog#index', :as => 'catalog_index'

  root :to => "catalog#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, format: false
  devise_scope :user do 
    match '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session
    match '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session
  end
  match "/authorize", to: 'derivatives#authorize'
  match "/autocomplete", to: 'object#autocomplete'

  match "object/:id", to: 'object#show'
  resources :media_objects, except: [:create] do
    member do
      put :update_status
      get :remove
      get :progress, :action => :show_progress
      get 'content/:datastream', :action => :deliver_content, :as => :inspect
      get 'track/:part', :action => :show, :as => :indexed_section
      get 'section/:content', :action => :show, :as => :pid_section
      get 'tree', :action => :tree, :as => :tree
    end
  end
  resources :master_files, except: [:new, :index] do
    member do
      get  'thumbnail', :to => 'master_files#get_frame', :defaults => { :type => 'thumbnail' }
      get  'poster',    :to => 'master_files#get_frame', :defaults => { :type => 'poster' }

      post 'thumbnail', :to => 'master_files#set_frame', :defaults => { :type => 'thumbnail', :format => 'html' }
      post 'poster',    :to => 'master_files#set_frame', :defaults => { :type => 'poster', :format => 'html' }
      post 'still',     :to => 'master_files#set_frame', :defaults => { :format => 'html' }
      get :embed
    end
  end

  match '/media_objects/:media_object_id/section/:id/embed' => 'master_files#embed'

  resources :derivatives, only: [:create]
  
  resources :comments, only: [:index, :create]

  namespace :admin do
    resources :groups, except: [:show] do 
      collection do 
        put 'update_multiple'
      end
      member do
        put 'update_users'
      end
    end
    resources :collections do
      member do
        get 'edit'
        get 'remove'
      end
    end
  end

  resources :dropbox, :only => [] do
    collection do
      delete :bulk_delete
    end
  end

  mount AboutPage::Engine => '/about(.:format)'
  

end

app/models/admin/collection.rb
# Copyright 2011-2014, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

require 'hydra/datastream/non_indexed_rights_metadata'
require 'hydra/model_mixins/hybrid_delegator'
require 'role_controls'
require 'avalon/controlled_vocabulary'
require 'avalon/sanitizer'

class Admin::Collection < ActiveFedora::Base
  include Hydra::AccessControls::Permissions
  include Hydra::ModelMixins::HybridDelegator
  include ActiveFedora::Associations
  include VersionableModel

  has_many :media_objects, property: :is_member_of_collection 
  has_metadata name: 'descMetadata', type: ActiveFedora::SimpleDatastream do |sds|
    sds.field :name, :string
    sds.field :unit, :string
    sds.field :description, :string
    sds.field :dropbox_directory_name
  end
  has_metadata name: 'inheritedRights', type: Hydra::Datastream::InheritableRightsMetadata
  has_metadata name: 'defaultRights', type: Hydra::Datastream::NonIndexedRightsMetadata, autocreate: true

  validates :name, :uniqueness => { :solr_name => 'name_sim'}, presence: true
  validates :unit, presence: true, inclusion: { in: Proc.new{ Admin::Collection.units } }
  validates :managers, length: {minimum: 1, message: 'Collection requires at least one manager'} 

  has_attributes :name, datastream: :descMetadata, multiple: false
  has_attributes :unit, datastream: :descMetadata, multiple: false
  has_attributes :description, datastream: :descMetadata, multiple: false
  has_attributes :dropbox_directory_name, datastream: :descMetadata, multiple: false
  
  delegate :read_groups, :read_groups=, :read_users, :read_users=,
           :visibility, :visibility=, :hidden?, :hidden=, 
           :local_read_groups, :virtual_read_groups, 
           to: :defaultRights, prefix: :default

  around_save :reindex_members, if: Proc.new{ |c| c.name_changed? or c.unit_changed? }
  has_model_version 'R3'
  after_validation :create_dropbox_directory!, :on => :create

  def self.units
    Avalon::ControlledVocabulary.find_by_name(:units)
  end

  def created_at
    @created_at ||= DateTime.parse(create_date)
  end

  def to_solr(solr_doc = Hash.new, opts = {})
    map = Solrizer::default_field_mapper
    solr_doc[ map.solr_name(:name, :stored_searchable, type: :string).to_sym ] = self.name
    super(solr_doc)
  end

  def managers
    edit_users & ( RoleControls.users("manager") | (RoleControls.users("administrator") || []) )
  end

  def managers= users
    old_managers = managers
    users.each {|u| add_manager u}
    (old_managers - users).each {|u| remove_manager u}
  end

  def add_manager user
    raise ArgumentError, "User #{user} does not belong to the manager group." unless (RoleControls.users("manager") + (RoleControls.users("administrator") || []) ).include?(user)
    self.edit_users += [user]
    self.inherited_edit_users += [user]
  end

  def remove_manager user
    return unless managers.include? user
    #raise "OneManagerLeft" if self.managers.size == 1 # Requires at least 1 manager

    self.edit_users -= [user]
    self.inherited_edit_users -= [user]
  end

  def editors
    edit_users - managers
  end

  def editors= users
    old_editors = editors
    users.each {|u| add_editor u}
    (old_editors - users).each {|u| remove_editor u}
  end

  def add_editor user
    self.edit_users += [user]
    self.inherited_edit_users += [user]
  end

  def remove_editor user
    return unless editors.include? user
    self.edit_users -= [user]
    self.inherited_edit_users -= [user]
  end

  def depositors
    read_users
  end

  def depositors= users
    old_depositors = depositors
    users.each {|u| add_depositor u}
    (old_depositors - users).each {|u| remove_depositor u}
  end

  def add_depositor user
    # Do not add an edit_user to read_users or they will be removed from edit_users
    unless self.edit_users.include? user
      self.read_users += [user]
      self.inherited_edit_users += [user]
    else
      raise "UserIsEditor"
    end
  end

  def remove_depositor user
    return unless depositors.include? user
    self.read_users -= [user]
    self.inherited_edit_users -= [user]
  end

  def inherited_edit_users
    inheritedRights.edit_access.machine.person
  end

  def inherited_edit_users= users
    p = {}
    (inherited_edit_users - users).each {|u| p[u] = 'none'}
    users.each {|u| p[u] = 'edit'}
    inheritedRights.update_permissions('person'=>p)
  end

  def self.reassign_media_objects( media_objects, source_collection, target_collection)
    media_objects.dup.each do |media_object|
      
      source_collection.remove_relationship(:is_member_of_collection, "info:fedora/#{media_object.pid}")
      source_collection.media_objects.delete media_object

      target_collection.add_relationship(:is_member_of_collection, "info:fedora/#{media_object.pid}")
      target_collection.media_objects << media_object

      media_object.collection = target_collection
      media_object.save(validate: false)
    end
    source_collection.save!
    target_collection.save!
  end

  def reindex_members
    yield
    reindex_media_objects
  end

  def reindex_media_objects
    media_objects.each{|mo| mo.update_index}
  end
  handle_asynchronously :reindex_media_objects

  def to_solr(solr_doc=Hash.new, *args)
    super
    solr_doc[Solrizer.default_field_mapper.solr_name("name", :facetable, type: :string)] = self.name
    solr_doc[Solrizer.default_field_mapper.solr_name("dropbox_directory_name", :facetable, type: :string)] = self.dropbox_directory_name
    solr_doc
  end

  def dropbox
    Avalon::Dropbox.new( dropbox_absolute_path, self )
  end

  def dropbox_absolute_path( name = nil )
    File.join(Avalon::Configuration.lookup('dropbox.path'), name || dropbox_directory_name)
  end

  private


    def create_dropbox_directory!
      name = self.dropbox_directory_name
      
      if name.blank?
        name = Avalon::Sanitizer.sanitize(self.name)
        iter = 2
        original_name = name.dup.freeze

        while File.exist? dropbox_absolute_path(name)
          name = "#{original_name}_#{iter}"
          iter += 1
        end
      end

      absolute_path = dropbox_absolute_path(name)
      
      unless File.directory?(absolute_path)
        begin
          Dir.mkdir(absolute_path)
        rescue Exception => e
          Rails.logger.error "Could not create directory (#{absolute_path}): #{e.inspect}"
        end
      end
      self.dropbox_directory_name = name
    end

end

app/controllers/admin/collections_controller.rb
# Copyright 2011-2014, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

class Admin::CollectionsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource except: [:remove, :show]
  respond_to :html
  
  # Catching a global exception seems like a bad idea here
  rescue_from Exception do |e|
    if e.message == "UserIsEditor"
      flash[:notice] = "User #{params[:new_depositor]} needs to be removed from manager or editor role first"
      redirect_to @collection
    else 
      raise e
    end
  end

  # GET /collections
  def index
    @collections = get_user_collections
  end

  # GET /collections/1
  def show
    @collection = Admin::Collection.find(params[:id])
    redirect_to admin_collections_path unless can? :read, @collection
    @groups = @collection.default_local_read_groups
    @users = @collection.default_read_users
    @virtual_groups = @collection.default_virtual_read_groups
    @visibility = @collection.default_visibility

    @addable_groups = Admin::Group.non_system_groups.reject { |g| @groups.include? g.name }
    @addable_courses = Course.all.reject { |c| @virtual_groups.include? c.context_id }
  end

  # GET /collections/new
  def new
    @collection = Admin::Collection.new
    respond_to do |format|
      format.js   { render json: modal_form_response(@collection) }
      format.html { render 'new' }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Admin::Collection.find(params[:id])
    respond_to do |format|
      format.js   { render json: modal_form_response(@collection) }
    end
  end
 
  # POST /collections
  def create
    @collection = Admin::Collection.create(params[:admin_collection].merge(managers: [user_key]))
    if @collection.persisted?
      User.where(username: [RoleControls.users('administrator')].flatten).each do |admin_user|
        NotificationsMailer.delay.new_collection( 
          creator_id: current_user.id, 
          collection_id: @collection.id, 
          user_id: admin_user.id, 
          subject: "New collection: #{@collection.name}"
        )
      end

      render json: modal_form_response(@collection, redirect_location: admin_collection_path(@collection))
    else
      render json: modal_form_response(@collection)
    end
  end
  
  # PUT /collections/1
  def update
    @collection = Admin::Collection.find(params[:id])
    if params[:admin_collection].present? && params[:admin_collection][:name].present?
      if params[:admin_collection][:name] != @collection.name && can?('update_name', @collection)
        @old_name = @collection.name
        @collection.name = params[:admin_collection][:name]
        if @collection.save
          User.where(username: [RoleControls.users('administrator')].flatten).each do |admin_user|
            NotificationsMailer.delay.update_collection( 
              updater_id: current_user.id, 
              collection_id: @collection.id, 
              user_id: admin_user.id,
              old_name: @old_name,
              subject: "Notification: collection #{@old_name} changed to #{@collection.name}"
            )
          end
        end
      end
    end

    ["manager", "editor", "depositor"].each do |title|
      if params["submit_add_#{title}"].present? 
        if params["add_#{title}"].present? && can?("update_#{title.pluralize}".to_sym, @collection)
          begin
            @collection.send "add_#{title}".to_sym, params["add_#{title}"]
          rescue ArgumentError => e
            flash[:notice] = e.message
          end
        else
          flash[:notice] = "#{title.titleize} can't be blank."
        end
      end
      
      remove_access = "remove_#{title}"
      if params[remove_access].present? && can?("update_#{title.pluralize}".to_sym, @collection)
          @collection.send remove_access.to_sym, params[remove_access]
      end
    end

    # If Save Access Setting button or Add/Remove User/Group button has been clicked
    if can?(:update_access_control, @collection)
      ["group", "class", "user"].each do |title|
        if params["submit_add_#{title}"].present?
          if params["add_#{title}"].present?
            if ["group", "class"].include? title
              @collection.default_read_groups += [params["add_#{title}"]]
            else
              @collection.default_read_users += [params["add_#{title}"]]
            end
          else
            flash[:notice] = "#{title.titleize} can't be blank."
          end
        end
        
        if params["remove_#{title}"].present?
          if ["group", "class"].include? title
            @collection.default_read_groups -= [params["remove_#{title}"]]
          else
            @collection.default_read_users -= [params["remove_#{title}"]]
          end
        end
    end

      @collection.default_visibility = params[:visibility] unless params[:visibility].blank? 

      @collection.default_hidden = params[:hidden] == "1"
    end
    
    @collection.save
    respond_to do |format|
      format.html { redirect_to @collection }
      format.js do 
        @collection.update_attributes params[:admin_collection]
        render json: modal_form_response(@collection)
      end
    end
  end

  # GET /collections/1/reassign
  def remove
    @collection = Admin::Collection.find(params[:id])
    @objects    = @collection.media_objects
    @candidates = get_user_collections.reject { |c| c == @collection }
  end

  # DELETE /collections/1
  def destroy
    @source_collection = Admin::Collection.find(params[:id])
    target_path = admin_collections_path
    if @source_collection.media_objects.length > 0
      @target_collection = Admin::Collection.find(params[:target_collection_id])
      Admin::Collection.reassign_media_objects( @source_collection.media_objects, @source_collection, @target_collection )
      target_path = admin_collection_path(@target_collection)
    end
    if @source_collection.media_objects.length == 0
      @source_collection.destroy
      redirect_to target_path
    else
      flash[:notice] = "Something went wrong. #{@source_collection.name} is not empty."
      redirect_to admin_collection_path(@source_collection)
    end
  end

end

app/views/admin/collections/_form.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<%= twitter_bootstrap_form_for @collection, remote: true, html: { modal: true } do |f| %>
  <%= f.text_field :name, class: 'span5' %>
  <%= f.text_area :description, rows: 3, class: 'span5'  %>
	<% if @collection.new? || can?(:update_unit, @collection)%>
		<%= f.select(:unit, "Unit", Admin::Collection.units) %>
	<% end %>	
	<%= f.submit class: 'btn btn-primary btn-stateful-loading', data: {loading_text: 'Saving...'} %>
	<a href="#" data-dismiss="modal" aria-hidden="true" class="btn">Cancel</a>
<% end %>

app/views/admin/collections/index.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% content_for :title do %>
  Collections
<% end %>

<div class='container'>
  <% unless @collections.empty? %>
    <h2>My Collections</h2>

    <table class='table table-striped'>
      <tbody>
      <% @collections.to_a.each do |collection| %>
        <tr>
          <td> <%= link_to collection.name, admin_collection_path(collection) %> </td>
          <td> <%= link_to(pluralize(collection.media_objects.size, 'item'), catalog_index_path('f[collection_ssim][]' => collection.name)) %>
							<% unpublishedCount = MediaObject.find("collection_ssim" => collection.name, 'workflow_published_sim' => "Unpublished").count%>
							<% if unpublishedCount > 0 %>
									<%=link_to("(#{unpublishedCount} unpublished)", catalog_index_path('f[collection_ssim][]' => collection.name, 'f[workflow_published_sim][]' => "Unpublished")) %>
							<% end %>
					</td>
          <td> <%= pluralize(collection.managers.size, 'manager') %> </td>
          <td> <%= collection.description %> </td>
          <td>
            <% if can?(:destroy, collection) %>
              <%= link_to('Delete', remove_admin_collection_path(collection), class: 'btn btn-mini btn-danger') %>
            <% else %>
              &nbsp;
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= link_to('Create Collection', new_admin_collection_path, remote: true, modal: true, class: 'btn btn-primary') unless cannot? :create, Admin::Collection %>
  <% else %>
    <div class="hero-unit">
      <h2>You don't have any collections yet</h2>

      <% if can? :create, Admin::Collection %>
        <p>Would you like to create one?</p>
        <div class="whitespace"></div>
        <p>
          <%= link_to('Create Collection', new_admin_collection_path, remote: true, modal: true, class: 'btn btn-primary btn-large')  %>
        </p>
      <% else %>
        <p>You'll need to be assigned to one</p>
      <% end %>

    </div>
  <% end %>

</div>


<% content_for :page_scripts do %>
  <script>
    new ModalLogic()
  </script>
<% end %>

app/views/admin/collections/new.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<%= render :partial => 'form' %>

app/views/admin/collections/remove.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% 
  item_count = "#{@objects.length} #{'item'.pluralize(@objects.length)}" 
  content_pronoun = @objects.length > 1 ? 'them' : 'it'
%>
<% if @collection.media_objects.length == 0 or @candidates.length > 0 %>
  <div class="row-fluid">
    <div class="alert alert-error">
      Are you certain you want to remove the collection <b><%=@collection.name%></b>?
    </div>
  </div>
  <%= twitter_bootstrap_form_for @collection, method: :delete do |f| %>
    <% if @objects.length > 0 %>
      <div class="row-fluid">
        <div class="alert">
        <fieldset>
          <legend>Reassign Existing Items</legend>
          <p>
            <b><%=@collection.name%></b> currently contains <%=item_count%>. Before you can 
            delete it, you must select a new collection to move <%=content_pronoun%> 
            into.
          </p>
          <%= select_tag :target_collection_id, options_from_collection_for_select(@candidates, "pid", "name") %>
        </fieldset>
        </div>
      </div>
    <% end %>
    <div class="row-fluid">
      <div class="btn-options">
        <%= f.submit 'Yes, I am sure', class: 'btn btn-danger' %>
        <%= link_to 'No, go back', admin_collections_path, class: 'btn' %> 
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row-fluid">
    <div class="alert alert-error">
      The collection "<%=@collection.name%>" cannot be deleted. It contains <%=item_count%>, 
      but you do not have sufficient rights to any other collections to reassign <%=content_pronoun%>.
    </div>
    <%= link_to 'Go back', :back, class: 'btn' %> 
  </div>
<% end %>

app/views/admin/collections/show.html.erb
<%#
Copyright 2011-2014, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% content_for :title do %>
  <%= @collection.name %>
<% end %>

<div class="row-fluid">
  <div class="span12">
    <div class="well">
    <h3><%= @collection.name %></h3>
    <p> <strong>Description:</strong> <%= @collection.description %> </p>
    <p> <strong>Unit:</strong> <%= @collection.unit %> </p>
    <%= link_to('Create An Item', new_media_object_path(collection_id: @collection.pid), class: 'btn btn-primary') if can? :create, MediaObject %>
    <%= link_to('List All Items', catalog_index_path('f[collection_ssim][]' => @collection.name), class: 'btn') %>
    <%= link_to('Edit Collection Info', edit_admin_collection_path(@collection), class: 'btn', remote: true, modal: true) if can? :update, @collection %>
    <br/><br>
    Or <a href='https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Collections+Guide#AvalonCollectionsGuide-UploadingviaBatch'><b>learn how to</b></a> create items using batch upload.
    </div>

    <%= twitter_bootstrap_form_for @collection, html: { class: "form-horizontal", id: 'access_control_form'}  do |co| %>

      <%= co.fieldset 'Assign Staff Roles' do %>

        <% if flash[:notice] %>
          <div class="alert alert-error span9">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <%= flash[:notice] %>
          </div>
        <% end %>
        <div class='staff-roles-section'>
          <%= render "modules/access_object",
            access_object: "manager",
            members: @collection.managers,
            autocomplete_model: 'user',
            object: @collection,
            input_disabled: cannot?( :update_managers, @collection ) %>
          <%= render "modules/access_object",
            access_object: "editor",
            members: @collection.editors,
            autocomplete_model: 'user',
            object: @collection,
            input_disabled: cannot?( :update_editors, @collection ) %>
          <%= render "modules/access_object",
            access_object: "depositor",
            members: @collection.depositors,
            autocomplete_model: 'user',
            object: @collection,
            input_disabled: cannot?( :update_depositors, @collection ) %>
        </div>
      <% end %>

      <div class="whitespace"></div>

      <%= co.fieldset 'Set Default Access Control for New Items' do %>
          <%= render "modules/access_control", { form: co, object: @collection, visibility: @collection.default_visibility, hidden: @collection.default_hidden? } %>	
					<% if can? :update_access_control, @collection %>
						<%= submit_tag "Save Access Settings", name: "save_access", class: "btn" %>
					<% end %>
      <% end %>
      
    <% end %>
  </div>
</div>

<style>
  fieldset .staff-roles-section { margin-left: 20px; }
  fieldset.item-access { margin-left: 20px;  }
  fieldset.item-discovery { margin-left: 20px; }
  fieldset.special-access { margin-left: 20px; }
  [name='save_access'] { margin-left: 20px;  }
</style>

<% content_for :page_scripts do %>
  <script>
    new ModalLogic()
  </script>
<% end %>